Better error message for misconfigured torchbench model
```
  File "/home/jansel/pytorch/./benchmarks/dynamo/torchbench.py", line 381, in load_model
    benchmark_cls.name = model_name
AttributeError: 'NoneType' object has no attribute 'name
```
becomes
```
  File "/home/jansel/pytorch/./benchmarks/dynamo/torchbench.py", line 381, in load_model
    raise NotImplementedError(f"{model_name}.Model is None")
NotImplementedError: torchrec_dlrm.Model is None
```

ghstack-source-id: 57b062a7e260ff6f4c0009260b775c806d26413c
Pull Request resolved: https://github.com/pytorch/pytorch/pull/114827